# Generated by Django 5.2.1 on 2025-05-17 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата Рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('student', 'Студент/Выпускник'), ('employer', 'Работодатель')], max_length=10, verbose_name='Роль')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('institute', models.CharField(blank=True, max_length=255, null=True, verbose_name='Институт')),
                ('employment_type', models.CharField(blank=True, choices=[('full', 'Полная занятость'), ('part_time', 'Частичная занятость')], max_length=20, null=True, verbose_name='Тип занятости')),
                ('desired_schedule', models.CharField(blank=True, choices=[('5/2', '5/2'), ('2/2', '2/2'), ('6/1', '6/1'), ('3/3', '3/3'), ('flexible', 'Гибкий график')], max_length=10, null=True, verbose_name='Желаемый график')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании (для работодателя)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
